### ISSUE TITLE
Generate multiple Output sentences using the simplify.py script.

### ISSUE THREAD

**Issue by Atharva-Phatak** [facebookresearch/muss#11]
Hello, I am trying to generate multiple simplifications using simplify.py. I understand the simplify.py uses _fairseq_generate function where you can specify num_hypothesis and best. I increase the num_hypothesis = 12 and nbest = 5. But I am still getting a single simplification whereas it should output multiple simplifications since nbest = 5. 

Can you guide me how to generate more simplifications ? @louismartin

**Comment by louismartin** [comment]
Hi, thanks for the question.
You can fiddle with the code here to find the top-k beam hypothesis: https://github.com/facebookresearch/muss/blob/278ec841a2bf029ed02feaf3224d623be7a697ea/muss/fairseq/base.py#L191

You could also generate other simplifications by changing the control tokens here: https://github.com/facebookresearch/muss/blob/278ec841a2bf029ed02feaf3224d623be7a697ea/muss/simplify.py#L47

**Comment by Atharva-Phatak** [comment]
@louismartin Can you explain more about what this line does ``` predictions = [hypotheses[hypothesis_num - 1] for hypotheses in all_hypotheses] ``` ?

**Comment by louismartin** [comment]
When `hypothesis_num=1` it will always take the first hypothesis of the beam search as output, if `hypothesis_num=2` it will always select the second ...
You can play around and inspect the variables by adding a breakpoint just before this line `import pdb; pdb.set_trace()`.

**Comment by Atharva-Phatak** [comment]
@louismartin Thank you for the respone I was able to generate multiple sentences. After reading your paper I understood that you are getting almost comparable results using ParaNMT dataset. 
Will you please elaborate the preprocessing steps you took while using  ParaNMT dataset ? By preprocessing I mean like cleaning, etc. 
I would very much appreciate if you will be able to tell me ?

**Comment by louismartin** [comment]
> @louismartin Thank you for the respone I was able to generate multiple sentences. After reading your paper I understood that you are getting almost comparable results using ParaNMT dataset.
> Will you please elaborate the preprocessing steps you took while using ParaNMT dataset ? By preprocessing I mean like cleaning, etc.
> I would very much appreciate if you will be able to tell me ?

Hi @Atharva-Phatak , I didn't clean the ParaNMT dataset and applied the same preprocessing as for wikilarge i.e. SentencePiece subword tokenization and fairseq binarization.

**Comment by Atharva-Phatak** [comment]
Can we finetune the pretrained MUSS model on further data. If so how do I do it ? which scripts to use ?

**Comment by louismartin** [comment]
Hi, I guess it is possible, you would have to modify the `fairseq-train` arguments to load the pretrained model: https://github.com/facebookresearch/muss/blob/04869c3058cd23c9e014dc3ca915c79e1f1ecba7/muss/fairseq/base.py#L106
Maybe just specifying a save_dir where the model is would be sufficient, but I'm not 100% sure. You should check the fairseq documentation for that.

**Comment by Atharva-Phatak** [comment]
Do you think training it on further data will improve simplifications ? Also I wanted to ask did you pretrain the BART model on mined data. Or did you use Mined data in a supervised fashion as sentence pairs ?

**Comment by louismartin** [comment]
Training on further data will improve the simplifications if the data is of good quality.
We took the BART pretrained model that's available open-source and then finetune it in a supervised fashion on the mined paraphrases as sentence pairs.
