### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2010' in position 48: ordinal not in range(128)

### ISSUE THREAD

**Issue by lmvasque** [facebookresearch/muss#13]
Hi @louismartin,

Thanks for this publishing this work, really nice! 

Regarding my inquiry, this is similar to the issue I've posted on [easse](https://github.com/feralvam/easse/issues/87). On this model, I'm also getting encoding errors when simplifying a list of sentences. I've added the same *encoding='utf-8'* and it stopped reporting this error.

Here are my diff files:
```
diff --git a/muss/preprocessors.py b/muss/preprocessors.py
index ee3dd86..6d438d5 100644
--- a/muss/preprocessors.py
+++ b/muss/preprocessors.py
@@ -131 +131 @@ class AbstractPreprocessor(ABC):
-        with open(output_filepath, 'w') as f:
+        with open(output_filepath, 'w', encoding='utf-8') as f:
@@ -139 +139 @@ class AbstractPreprocessor(ABC):
-        with open(output_filepath, 'w') as f:
+        with open(output_filepath, 'w', encoding='utf-8') as f:

diff --git a/muss/utils/helpers.py b/muss/utils/helpers.py
index 25210d8..78a5f41 100644
--- a/muss/utils/helpers.py
+++ b/muss/utils/helpers.py
@@ -91 +91 @@ def open_files(filepaths, mode='r'):
-        files = [Path(filepath).open(mode) for filepath in filepaths]
+        files = [Path(filepath).open(mode, encoding='utf-8') for filepath in filepaths]
@@ -137 +137 @@ def write_lines(lines, filepath=None):
-    with filepath.open('w') as f:
+    with filepath.open('w', encoding='utf-8') as f:
@@ -148 +148 @@ def yield_lines(filepath, gzipped=False, n_lines=None):
-    with open_function(filepath, 'rt') as f:
+    with open_function(filepath, 'rt', encoding='utf-8') as f:
@@ -325 +325 @@ def log_std_streams(filepath):
-    log_file = open(filepath, 'w')
+    log_file = open(filepath, 'w', encoding='utf-8')

diff --git a/scripts/simplify.py b/scripts/simplify.py
index 464129c..95a6231 100644
--- a/scripts/simplify.py
+++ b/scripts/simplify.py
@@ -26,0 +27,2 @@ if __name__ == '__main__':
+        s = s.encode('utf-8')
+        c = c.encode('utf-8')
```

I'll appreciate if you could add these fixes :)

Thanks,

Laura

**Comment by louismartin** [comment]
Hi Laura,
Thanks for the issue and sorry for the delay.
Can you open a pull request on the repo with your proposed changes ? :)
Thanks

**Comment by louismartin** [comment]
By the way, which version of python are you using?

**Comment by lmvasque** [comment]
> By the way, which version of python are you using?
> ([this post](https://stackoverflow.com/questions/48347331/python-unicodeencodeerror-ascii-codec-cant-encode-character-in-position-0-o) makes me think that it comes from using python 2.X)

No.. actually is Python 3. This is what I have in my environment:
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)

**Comment by lmvasque** [comment]
> Hi Laura,
> Thanks for the issue and sorry for the delay.
> Can you open a pull request on the repo with your proposed changes ? :)
> Thanks

Hi Martin,
No worries, I'm still working on it. Sure, let me try that. I'll let you know when is ready :)
Thanks!

**Comment by lmvasque** [comment]
> > Hi Laura,
> > Thanks for the issue and sorry for the delay.
> > Can you open a pull request on the repo with your proposed changes ? :)
> > Thanks
> 
> Hi Martin,
> No worries, I'm still working on it. Sure, let me try that. I'll let you know when is ready :)
> Thanks!

It's ready now, however, I have no idea about the CLA.. let me ask about that before.
