### ISSUE TITLE
Preprocess the mined corpus with new control tokens

### ISSUE THREAD

**Issue by psawa** [facebookresearch/muss#14]
Hi, 

I am exploring MUSS for sentence simplification, and I would like to add restrictions to the simplification style.  Let's say that I'd like to ban the generation of sentences in complicated tenses, for example. 

My idea is to preprocess the mined corpus with new control tokens that would fit my needs, in addition to the 4 control tokens presented in the paper.  

Is it a technique that makes sense to you, and if so, Is there a prefered way to re-annotate  the corpus using the code of the repo? 

Thanks,

**Comment by louismartin** [comment]
Hi,

Yes that would be a good idea.
You would have to add a new preprocessor class here: https://github.com/facebookresearch/muss/blob/main/muss/preprocessors.py
(Sorry there is not much documentation, maybe try to get inspiration from [this one](https://github.com/facebookresearch/muss/blob/ed70446abdbebce4513123c376e40f5ff05290a0/muss/preprocessors.py#L281)).

Then you would need to train the model again using [scripts/train_model.py](https://github.com/facebookresearch/muss/blob/main/scripts/train_model.py) but add your new preprocessor along with other access preprocessors [here](https://github.com/facebookresearch/muss/blob/ed70446abdbebce4513123c376e40f5ff05290a0/muss/mining/training.py#L55).

**Comment by psawa** [comment]
Many thanks, I will investigate this!
