### ISSUE TITLE
Could you provide spm_tokenizer and kenlm model

### ISSUE THREAD

**Issue by akafen** [facebookresearch/muss#20]
```
@lru_cache(maxsize=10)
def get_spm_tokenizer(model_dir):
    merges_file = model_dir / 'spm_tokenizer-merges.txt'
    vocab_file = model_dir / 'spm_tokenizer-vocab.json'
    return SentencePieceBPETokenizer(vocab_file=str(vocab_file), merges_file=str(merges_file))


@lru_cache(maxsize=10)
def get_kenlm_model(model_dir):
    model_file = model_dir / 'kenlm_model.arpa'
    return kenlm.Model(str(model_file))
```

I find dataset generation need spm_tokenizer and kenlm_model.arpa, could you provide them?

**Comment by louismartin** [comment]
Hi @akafen , let me come back to you as soon as possible on this.

**Comment by akafen** [comment]
> Hi @akafen , let me come back to you as soon as possible on this.

Ok.thanks

**Comment by louismartin** [comment]
Hi @akafen , sorry for the delay.
Can you please tell me which model/language you are using?
Maybe you can just use `print(model_dir)` in each of the functions you mentioned.

**Comment by akafen** [comment]
> Hi @akafen , sorry for the delay.
> Can you please tell me which model/language you are using?
> Maybe you can just use `print(model_dir)` in each of the functions you mentioned.
@louismartin  I am trying to reproduce en_mined model, but I need to generate dataset first. But dataset generation need spm_tokenizer and kenlm_model.arpa and I don't know how to get them

**Comment by akafen** [comment]
Hello @louismartin ,you could tell me how to generate 'spm_tokenizer-merges.txt' and 'spm_tokenizer-vocab.json',that would be also enough

**Comment by louismartin** [comment]
I'm closing this issue for now but feel free to comment or open again if needed.

**Comment by chirico85** [comment]
Dear @louismartin ,
Thank you for the great job! I am fascinated by your research.

Do you also have a german language model you could provide?

Best regards!

**Comment by louismartin** [comment]
Hi @chirico85 
Unfortunately we have trained the model only for English, French and Spanish.
Our code could be used to train a model in german but it would require non-trivial amount of compute / work.

**Comment by chirico85** [comment]
For anyone interested in creating a kenlm model in another language, here is a helpful [repo](https://github.com/tiefenauer/wiki-lm). Further, I found some help to train a tokenizer, resulting in a merges.txt and vocab.json, reading this [blog](https://towardsdatascience.com/transformers-from-scratch-creating-a-tokenizer-7d7418adb403).

@louismartin, I followed both explanations and I got a kenlm model.arpa file (3GB), trained on a wikipedia corpus, and corresponding merges.txt and vocab.json. However, when I instantiate the tokenizer as done in kenlm.py, the following error occurs:

`Exception: Error while initializing BPE: Merges text file invalid at line 101`

According to this [Issue](https://github.com/huggingface/tokenizers/issues/588) and as detected in my case, there is an empty line at 101 (and some other lines) in my merges.txt. However, their 'solution ' in the mentioned issue does not satisfy me, yet. 

Did you detect the same issues while training your kenlm models and tokenizer? I thought I had cleaned up empty lines within the processed corpus material before training both. It appears empty lines in the training corpus might  cause the empty lines within merges.txt.... right?

I have another question concerning the 'slope' variable within preprocessing.py in the has_low_lm_prob method. How did you set the size of the values for the given languages to filter text resulting in a low probability of being 'predicted'? Do you have any references or estimations you can share with, especially for German?

I also wonder why my 3-gram kenlm model.arpa file (3GB) is so much bigger than your models.

Thanks a lot again!
Regards

**Comment by louismartin** [comment]
Hi @chirico85 and sorry for the delay.
I don't think I had problems with the merges.txt file on my side.

Hum the slope was selected manually by computing the probabilities on many sentences on my corpus and choosing a threshold that seemed reasonable, I probably should have designed a more reproducible for that. I think it does not have a big impact though.

No idea for the size of the model.arpa file :O
