### ISSUE TITLE
Hello, when I run the pretrained model I get this error

### ISSUE THREAD

**Issue by oskrmiguel** [facebookresearch/muss#24]
Hello, when I run the pretrained model I get this error

] [-t TARGET] [--load-alignments]
                   [--left-pad-source BOOL] [--left-pad-target BOOL]
                   [--max-source-positions N] [--max-target-positions N]
                   [--upsample-primary UPSAMPLE_PRIMARY] [--truncate-source]
                   [--num-batch-buckets N] [--eval-bleu]
                   [--eval-bleu-detok EVAL_BLEU_DETOK]
                   [--eval-bleu-detok-args JSON] [--eval-tokenized-bleu]
                   [--eval-bleu-remove-bpe [EVAL_BLEU_REMOVE_BPE]]
                   [--eval-bleu-args JSON] [--eval-bleu-print-samples] --langs
                   LANG [--prepend-bos]
                   data
simplify.py: error: unrecognized arguments: Notebooks/muss/resources/models/muss_es_mined/model.pt

**Comment by louismartin** [comment]
I'll close the issue for now but feel free to reopen when needed

**Comment by oskrmiguel** [comment]
> 
> 
> Hello, thanks for the issue! What command did you run exactly? I think you shouldn't pass the path to the model but just the model name (see help).

Hello it's the command 
!python '/content/drive/MyDrive/Colab Notebooks/muss/scripts/simplify.py' '/content/drive/MyDrive/Colab Notebooks/muss/scripts/examples.es' --model-name muss_es_mined  

Running in Colab

**Comment by nishkalavallabhi** [comment]
I got the same error, running on terminal.

**Comment by nishkalavallabhi** [comment]
I got the same error, running on terminal. I used the command as described in the readme.
python scripts/simplify.py scripts/examples.en --model-name muss_en_wikilarge_mined

**Comment by louismartin** [comment]
Hi, thanks for reporting that issue.
Can you paste the full error here please?
