### ISSUE TITLE
Simplify in French

### ISSUE THREAD

**Issue by Dadox** [facebookresearch/muss#28]
![2021-11-02](https://user-images.githubusercontent.com/1596756/139830336-21684d7f-4a26-4f0a-8c78-6a3516d22dc7.png)

Could you check the simplify French version ? 
In your French exemple file, after running the simplification, the cat become a dog ...

Thank's

**Comment by louismartin** [comment]
Hi,

Yes I think this is just a model error here... Not sure if there is a quick fix for that.
