### ISSUE TITLE
AttributeError: module 'faiss' has no attribute 'METRIC_L2_DIST

### ISSUE THREAD

**Issue by NomadXD** [facebookresearch/muss#3]
I'm getting the following error when I execute `python scripts/mine_sequences.py` . 
```
Traceback (most recent call last):
  File "scripts/mine_sequences.py", line 118, in <module>
    train_sentences, get_index_name(), get_embeddings, faiss.METRIC_L2_DIST, base_index_dir
AttributeError: module 'faiss' has no attribute 'METRIC_L2_DIST
```
Getting this error in both faiss-gpu and faiss-cpu. However when I use it as ` faiss.METRIC_L2` (without DIST), it works fine. Any idea about the issue ?

**Comment by louismartin** [comment]
Hi @NomadXD 
That's a good question, maybe it was changed in faiss.
I will rename it to METRIC_L2 then and hope it doesn't bring unforeseen bugs.

**Comment by NomadXD** [comment]
@louismartin Thank you. Is there any specific configuration that I can use for training a small test sample ??? Like in `cc_net` we can provide the config as a json and tweak the config for a test sample. I just want to do few modifications and test it with a sample before training on actual data.

**Comment by louismartin** [comment]
Hi @NomadXD , I'm reoppening the issue for your question. I'm currently working on a simple script to do what you asked, hope to have some udpates for you soon.

**Comment by NomadXD** [comment]
@louismartin Thank you very much. Really appreciate that !!

**Comment by louismartin** [comment]
I just made the training script simpler if you want to train a single model on google colab.
Tell me if that works well on your end and we can close the issue.

If you want to also mine the data, you will have to run all the mining pipelline, I am not sure that it will work on google colab, but you can try.

**Comment by louismartin** [comment]
Hi @NomadXD , you need to install spacy's model with `python -m spacy download en_core_web_md`

**Comment by louismartin** [comment]
Closing but feel free to open a new issue if you have further questions or problems
