### ISSUE TITLE
Mining sequences: reading in the CC dataset

### ISSUE THREAD

**Issue by izaskr** [facebookresearch/muss#30]
Hi,
Thank you for the great repo. I'm trying to mine sequences with `scripts/mine_sequences.py`, but the data does not get read at all.

Since I was unable to download the data from https://github.com/facebookresearch/cc_net as requested, I downloaded some parts of the French Common Crawl from the OSCAR corpus. When the prompt asks for the path to the data, I point to the directory which has a couple of *.txt.gz files along with the *.jsonl.gz meta data files. 

After inspecting the error raised (`ValueError: need at least one array to concatenate`) I saw none of the data got either read or written. 

What should the directory from the `input` prompt include? That would help me answer these questions:
- In [line 83](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L83), the subdirectories of `raw_original_dir` are checked to find and list *.json.gz files, but there are none there - should they be created in lines [59-63](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L59)?
- Similarly, [line 106](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L106) is looking for *.txt.gz files, but there are none in the `dataset_dir` directory
- I also don't understand the condition in [line 68](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L68): the directories already exist, so none of the jobs will be executed. 

Thanks!

**Comment by louismartin** [comment]
Hi @izaskr , thanks for raising the issue and sorry for the late response.

The `*.json.gz` files are the format that is used in CCNet if I remember correctly.
I think if you want to use OSCAR you would have to replace the glob to find the files in the OSCAR format and then adapt the [`split_ccnet_shard`](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/muss/mining/preprocessing.py#L29) logic to OSCAR.

The `*.txt.gz` files on the other hand are created by [`sentence_tokenize_subshard`](https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/muss/mining/preprocessing.py#L85) by reading the `json.gz` files and converting them to `txt.gz`.
