### ISSUE TITLE
Can not get alignment to interpret  the model behavior 

### ISSUE THREAD

**Issue by sc16s2w** [facebookresearch/muss#33]
Hi, I am currently trying to get the output of  alignment, source sentence and hypotheis, I want to print the source sentence, the alignment, the hypothesis, but my output is just shown as follows: 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/44282471/153726843-055042bc-4466-4b85-be00-1daec7e50ab3.png">

 it is difficult for me to connect the score with the original sentence, I just want the output to be the same as the example like this: 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/44282471/153726849-da8d46f3-e5b7-4a49-9561-e7322b35b94f.png">
Can you tell me how to solve my problem?

**Comment by louismartin** [comment]
Hi @sc16s2w and sorry for the delay.

I think this is due to the fact that BART uses GPT2 bpe and then sends the ids to fairseq hence why the text is not shown.
I don't think there is a simple way to recover the alignment.

**Comment by sc16s2w** [comment]
Thanks for your help, I have already solved this question!

**Comment by chirico85** [comment]
Hi @sc16s2w, 
Please, could you share your solution?
Thanks.
