### ISSUE TITLE
Vectorizing new control tokens

### ISSUE THREAD

**Issue by annadmitrieva** [facebookresearch/muss#41]
This question touches on [this issue](https://github.com/facebookresearch/muss/issues/14). I have looked through the source code provided in that issue, but still don't understand how is the model's vocabulary updated when new control tokens are added. Could you please provide a more detailed explanation on that? Also, it is unclear how many unique vocabulary instances are added per token. I know that in [access](https://github.com/facebookresearch/access/), according to the paper, 40 unique values per control token are added, but what if the new token needs much less values?

**Comment by louismartin** [comment]
Hi @annadmitrieva and thank you for the question.
We don't update the subword / sentencepiece vocabulary with the special control tokens. We use the tokenizer that is provided with BART and just use it on the plain text tokens.
This might look something like: text = "<LENGTH_0.9>" => subword_tokens = ["<", "LEN", "GTH", "_", "0.9", ">"]

So each special control token, is tokenized into multiple subword tokens that already exist in the model vocabulary.

In ACCESS, the 40 unique values correpond to the discretization (e.g. with a step of 0.05: "<LENGTH_0.9>", "<LENGTH_0.95>", "<LENGTH_1.0>" etc.). This discretization has no impact on the subword vocabulary.

**Comment by annadmitrieva** [comment]
Thank you for the detailed explanation! Closing the issue now.
