### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by hajijesmaili** [facebookresearch/muss#7]
Hello
when I run this commmand
cd muss/
pip install -e .

my cmd log stop here
Please help me
![error](https://user-images.githubusercontent.com/35924238/119166616-17035880-ba74-11eb-930f-3ce13470e48d.png)

**Comment by hajijesmaili** [comment]
I run this command in Windows OS

**Comment by louismartin** [comment]
Hi, thanks for the issue.

Windows is sadly not supported, only Linux or macOS. I am afraid you will be on your own on this one.

**Comment by hajijesmaili** [comment]
Thanks
I run this on Mac OS  Unfortunately I faced this error
[](url)

**Comment by hajijesmaili** [comment]
Collecting faiss-gpu
  Downloading faiss-gpu-1.7.0.tar.gz (34 kB)
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/apple/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Users/apple/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/Users/apple/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/apple/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 370, in _resolve_one
    assert req_to_install.is_direct
AssertionError

**Comment by hajijesmaili** [comment]
![Uploading Screen Shot 2021-05-22 at 12.05.29 PM.png…]()

**Comment by louismartin** [comment]
Thanks for pointing this out, it seems like faiss-gpu is not straightforward to install on macos.
I see three possible solutions
1) Use faiss-cpu instead of faiss-gpu in requirements.txt
2) Use linux instead of macOS
3) Install faiss GPU following instructions you can find such as: https://gist.github.com/maxime/ef3fae0c2cf255fcb5c123978ec70da5

**Comment by hajijesmaili** [comment]
just a question
does your method simplify this kind of sentences?
"Barack Obama, a former U.S president, was born in Hawai"
to this splits?
"a former U.S president, was born in Hawai"
"Barack Obama, was born in Hawai"

**Comment by louismartin** [comment]
Hi @hajijesmaili 
I am not sure, you can verify it by using the `scripts/simplify.py` script and giving a file as input containing your sentence.
